### ISSUE TITLE
Determine mapping environment

### ISSUE THREAD

**Issue by hsolbrig** [cancerDHC/Terminology#18]
Determine who will perform the actual value set mapping work which, in turn, will determine the environment they will be working in.  As an example, if NCI will be supporting the mapping work, then the environment will be the existing NCI mapping environment.  If other groups, other tools may need to be incorporated or, as a last resort, developed.   In any case, these tools will need to be connected to the value set content and services as developed here

**Comment by jiaola** [comment]
We have decided to use SSSOM to represent the mappings. The mappings will be stored in a neo4j graph model based on the iso-11179 model. 

Development is in https://github.com/HOT-Ecosystem/crdc-node-models
