### ISSUE TITLE
Assemble existing value sets in tabular format

### ISSUE THREAD

**Issue by hsolbrig** [cancerDHC/Terminology#8]
Scrape the various input sources pulling the permissible values and their concept links in anticipation of the mapping document.

Documentation: https://docs.google.com/document/d/1Iu2HrbKykeNe3Q23NYEkHlWONEUV9GuWVNhzElf84TY/edit?pli=1#

Tabular format: https://docs.google.com/spreadsheets/d/1UmPgSM1MGTST-sxHQEyUROWmShUYmgABTa42N_Gu-Fg/edit#gid=810954098

**Comment by jiaola** [comment]
The GitHub repo for this work: https://github.com/HOT-Ecosystem/crdc-node-models

**Comment by jiaola** [comment]
Close this ticket since tabular format have been created and reviewed by the DH group
